x-piston-run-budget-ms: &piston-run-budget-ms '10000'
x-piston-compile-budget-ms: &piston-compile-budget-ms '60000'
version: '3.2'

services:
    api:
        build: api
        container_name: piston_api
        privileged: true
        restart: always
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        environment:
            PISTON_COMPILE_TIMEOUT: *piston-compile-budget-ms
            PISTON_COMPILE_CPU_TIME: *piston-compile-budget-ms
            PISTON_RUN_TIMEOUT: *piston-run-budget-ms
            PISTON_RUN_CPU_TIME: *piston-run-budget-ms
            PISTON_REPO_URL: http://repo:8000/index

    repo: # Local testing of packages
        build: repo
        container_name: piston_repo
        command: ['--no-build'] # Don't build anything
        volumes:
            - .:/piston
