x-piston-run-budget-ms: &piston-run-budget-ms '10000'
x-piston-compile-budget-ms: &piston-compile-budget-ms '60000'
version: '3.2'

services:
    api:
        build: api
        image: piston
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        environment:
            PISTON_COMPILE_TIMEOUT: *piston-compile-budget-ms
            PISTON_COMPILE_CPU_TIME: *piston-compile-budget-ms
            PISTON_RUN_TIMEOUT: *piston-run-budget-ms
            PISTON_RUN_CPU_TIME: *piston-run-budget-ms
        tmpfs:
            - /tmp:exec
